Assets for iPhone X and Android
associazione-rousseau/camelot-flutter pull request #55
Opened 2019-11-14 03:15 UTC by aledeniz

As per #32 here are some Assets exported from AI.
Half are black, half are rosso corsa. Half for landscape, half for portait. Half for iPhone X, half for Android.
As discussed, these are not screens, but are are meant to be centered through a widget.
I have also updated the AI artwork.

2019-11-14 21:47 UTC, emanuelconunaemme approved these changes

2019-11-14 21:48 UTC, emanuelconunaemme requested changes
The space in the file names can be a problem. What do you think?

2019-11-14 23:06 UTC, aledeniz commented
@emanuelconunaemme done.

`Dir | Rename-Item –NewName { $_.name –replace “ “,”_” }`

2019-11-15 00:59 UTC, emanuelconunaemme approved these changes

2019-11-15 00:59 UTC, merged